name: 自动部署 Hexo

# 只监听 source 分支的改动
on:
  push:
    branches:
      - main

# 自定义环境变量
env:
  GIT_USER: eacls
  GIT_EMAIL: eacls@eacls.top


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13]

    steps:
      - name: 开始运行
        uses: actions/checkout@v1

      - name: 设置 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 安装 Hexo CI
        run: 
          npm install hexo-cli -g

      - name: 缓存
        uses: actions/cache@v1
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

      - name: 安装插件
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: 
          npm install

      - name: 部署博客
        run: 
          hexo clean && hexo g
          cd ./public
          git init
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          git add .
          git commit -m "Update"
          git push --force --quiet "https://${{secrets.GH_TOKEN}}@eacls.github.io.git" main:main